services:
  - type: web
    name: handily-commerce-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
