// <auto-generated />
using System;
using HandilyCommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HandilyCommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HandilyCommerceDbContext))]
    partial class HandilyCommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HandilyCommerce.Domain.Changelog.ChangelogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PrNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ProductVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("ChangelogEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a10c0000-0011-4000-8000-00000000000b"),
                            Label = "Release Mirror",
                            MergedAt = new DateTimeOffset(new DateTime(2026, 9, 10, 22, 44, 17, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PrNumber = 11,
                            ProductVersion = "0.3.0",
                            Summary = "Changelog API for the FE \"What's new\" modal: hexagonal ports, GET /api/v1/changelog from embedded JSON seed, and merge workflow to append Major/Mirror entries.",
                            Title = "feat: changelog API for Major/Mirror releases"
                        },
                        new
                        {
                            Id = new Guid("a10c0000-0010-4000-8000-00000000000a"),
                            Label = "Release Mirror",
                            MergedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 14, 39, 41, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PrNumber = 10,
                            ProductVersion = "0.2.0",
                            Summary = "Adds Scalar UI over the existing OpenAPI document in all environments, including Production on Render.",
                            Title = "feat(A2): Scalar OpenAPI UI"
                        },
                        new
                        {
                            Id = new Guid("a10c0000-0007-4000-8000-000000000007"),
                            Label = "Release Mirror",
                            MergedAt = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 41, 37, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PrNumber = 7,
                            ProductVersion = "0.1.0",
                            Summary = "Introduces product Versioning separate from the API route version, with Directory.Build.props baseline 0.1.0 and the Release label process.",
                            Title = "chore: Versioning 0.1.0 + Release labels process"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
